micronaut:
  application:
    name: micronaut-tracing-issue-3
  server:
    host: 0.0.0.0
    port: 8080

tracing:
  # instrument-threads does not change anything
  # instrument-threads: true
  jaeger:
    enabled: true
    sampler:
      type: probabilistic
      probability: 1
